# Generated by Django 3.1.1 on 2021-10-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211006_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fb_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ok_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pinterest_url',
        ),
    ]
